FROM python:3.11-slim

WORKDIR /app

# Кэширование pip для ускорения пересборки
RUN pip install --upgrade pip && \
    pip cache dir

# Копируем только requirements для кэширования слоя зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
